---
kind: Namespace
apiVersion: v1
metadata:
  name: test-polkassembly
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: gitlab
  namespace: test-polkassembly
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gitlab
  namespace: test-polkassembly
subjects:
- kind: ServiceAccount
  name: gitlab
  namespace: test-polkassembly
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: test-polkassembly-io
  namespace: test-polkassembly
spec:
  domains:
    - test.polkassembly.io
